title: SAHIL CHAWLA # name of the site
author: SAHIL CHAWLA # name of site's author
email: sahil.chawla@gmail.com # email of site's author
url: https://csahil.github.io # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
    I work at SIG covering A&D and Oilfield Services. In 2020 I graduated UC Berkeley with a double major in Economics and Interdisciplinary Studies (my own program of psych/history/sociology) and wrote my thesis about <a href="https://csahil.github.io/assets/Chess.pdf">chess</a>.
<br>
    I spend a lot of time thinking about investing — currently for my PA and soon as a career. Here's some of my work. I have owned most of these stocks at some point.

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%m-%Y" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
